### ISSUE TITLE
BUG: to_graph crashes when  'oneway' is not specified

### ISSUE THREAD

**Issue by bramson** [HTenkanen/pyrosm#100]
While collecting my network windows, I got the following error on the 22nd grid that caused the script to crash.

```
  File "G:/My Drive/Codebase/ExtractingOSMData_v02.py", line 252, in getOSMnetwork
    thisWalkingGraph = thisAreaData.to_graph(nodes, edges, graph_type="networkx", osmnx_compatible=False, retain_all=True)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\pyrosm\pyrosm.py", line 756, in to_graph
    network_type, retain_all, osmnx_compatible)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\pyrosm\graphs.py", line 145, in to_networkx
    network_type)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\pyrosm\graphs.py", line 26, in get_directed_edges
    col=col)

ValueError: Required column 'oneway' does not exist in edges.
```

It is not hard to imagine that lots of roads fail to specify whether it is one-way or not, especially for pedestrian or footpath edges.

I think that, in these cases, it would be better to use a default of `oneway=false` instead of crashing.
Similar reasonable defaults could/should be done for other required variables.

And maybe it could throw a warning instead of an error...although that may explode my terminal, so please make that optional.
(i.e., I want to know if this is happening when testing, but if I decide I'm okay with it, I don't need to see thousands of warning messages in my console feed.)

...or maybe I misunderstand the meaning of this error.

**Comment by HTenkanen** [comment]
@bramson Thanks for reporting this 🙏

Hmm, yes I believe this is a situation where indeed none of the ways in your data has a tag "oneway". Didn't think that this might happen but surely it does, as shown here.

I think the solution could indeed be to assume that all roads are bidirectional in such case, and raise a warning. 👍 Thanks! Will fix this asap.

**Comment by HTenkanen** [comment]
As a quick fix, you can add the column "oneway" to edges with value None if the column does not exist, before using the to_graph() function.

**Comment by HTenkanen** [comment]
@bramson Okay, now this should be fixed in the master. Thanks for pointing this out! 👍
