### ISSUE TITLE
QUESTION: get_network returns None instead of an empty dataframe when no nodes/edges are found

### ISSUE THREAD

**Issue by bramson** [HTenkanen/pyrosm#103]
As the title says, when an area enclosed by a bounding polygon does not contain any nodes/edges, the `get_network` module returns `None` instead of empty GeoDataFrames for nodes and edges.

This seemed reasonable at first, but I need to test for whether any edges are returned before running code on those edges.
Testing for `len(edgesDF) > 0` doesn't work because `None` has no length.  
Testing for `edgesDF ~= None` doesn't work because the truth value of a GeoDataFrame is ambiguous.
Using `if isinstance(edgesDF, gp.GeoDataFrame):` and then `len(edgesDF) > 0` works, but ...

if `get_network` returned an empty GeoDataFrame instead of `None` then I think IO features would become a bit more robust.

Of course, maybe there is a good reason that I'm not considering where returning `None` is actually better...so maybe it's not a bug at all, and anyway the work-around was simple enough.

**Comment by HTenkanen** [comment]
Hmm, you should be able to do following , no? :

```python
# If this is a loop
nodes, edges = osm.get_network(nodes=True)
if edges is None:
   continue
```

**Comment by HTenkanen** [comment]
Anyway, returning `None` instead of an empty GeoDataFrame is somewhat a matter of taste. I think it is more intuitive to get "nothing" instead of an empty object of some sort if there is no data.

**Comment by bramson** [comment]
I thought that would work too, but the problem is that when `edges` IS a geodataframe, `if edges = None` throws the error `the truth value of a GeoDataFrame is ambiguous`.  

I agree it's just s matter of taste, and I agree that returning `None` in that case is more intuitive.  But I ran into the problem of getting incommensurable data types depending on whether edges were found or not.  

But like I said, the workaround was easy enough with `if isinstance(edgesDF, gp.GeoDataFrame):`, so I was really just bringing this to your attention in case it was an oversight.  I also think it would be pretty rare to specify a region and have it return no edges...only in cases like mine where I'm sweeping an area with a grid rather than selecting a particular area of actual interest.

**Comment by HTenkanen** [comment]
Hmm, I am actually testing against None in the source codes in many places so it should work. (ie continue doing something with gdf if it is not None)

If you check the value of your variable using a "negation" approach, it should give True only when the variable is None and in every other case give False. 
 And following this approach (negation) you can do something like:
```python
if myvariable is not None:
   # continue doing something with dataframe

```
I'll check with computer later but ^ should work.
