### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by emilianosantin** [HTenkanen/pyrosm#107]
Is there any distance function that I could use to measure minimum distance (straight line) between a set of imported points/address and natural/ coastline/waterways without using  network tools? 

Thanks 

Emiliano

**Comment by HTenkanen** [comment]
@emilianosantin Hi! No `pyrosm` does not include any of these, but you can use [geopandas](https://geopandas.org/) to calculate distances between objects. One approach is to loop over your point geometries (with `apply()`) and calculate the distance between the given point to all other geometries (e.g. waterways), and from those find out which is the minimum distance.

There is also some course material about doing nearest neighbor analysis using Python, but these assume that you have two point datasets:
https://autogis-site.readthedocs.io/en/latest/notebooks/L3/06_nearest-neighbor-faster.html

**Comment by emilianosantin** [comment]
Thanks for your help!
