### ISSUE TITLE
Pyrosm Doesn't Provide Access to Many Markets

### ISSUE THREAD

**Issue by kerinb** [HTenkanen/pyrosm#110]
I have been using pyrosm for a little while (it's great) but one thing I have noticed is that I am restricted on the countries I can appear to be able to access - For example I cannot access data for Trinidad and Tobago, Montserrat or Barbuda etc..

If there is a work around to getting access to this data, I would appreciate - but from what I can see, there's no way to access. 

from pyrosm import OSM
from pyrosm import get_data
fp = get_data("Trinidad and Tobago")

osm = OSM(fp)
osm

ValueError: The dataset 'trinidad and tobago' is not available

**Comment by HTenkanen** [comment]
@kerinb Thanks for your comment and nice to hear that it has been useful for you 👍🏻 The `get_data()` functionality is indeed a bit limited and it only works if a subset of OSM data can be found from Geofabrik. As you can see from here: http://download.geofabrik.de/central-america.html 

Trinidad and Tobago is not directly available from Geofabrik. BUT, there is a workaround and it is possible to fetch PBF data from anywhere in the world. You can read details from the documentation of the tool:
https://pyrosm.readthedocs.io/en/latest/basics.html#what-to-do-if-you-cannot-find-the-data-for-your-area-of-interest 

Hopefully this helps!

**Comment by HTenkanen** [comment]
Alternatively, you could consider using OSMnx to fetch the data for these areas.

**Comment by kerinb** [comment]
@HTenkanen Thanks for the quick response and the explanation - That all makes sense! I will take a look at accessing the PBF files. Thank you for the help on this, I appreciate it :)

**Comment by HTenkanen** [comment]
Great! Feel free to ask again if you have any troubles 👍🏻
