### ISSUE TITLE
Can't import OSM from pyrosm, KeyError MISSING

### ISSUE THREAD

**Issue by awa5114** [HTenkanen/pyrosm#119]
I tried to do a basic test run with `pyrosm` on Geofabrik's us-northeast-latest PBF extract and the example provided in `pyrosm` docs:
```
from pyrosm import OSM
from pyrosm import get_data
fp = get_data("us-northeast-latest.osm.pbf")
# Initialize the OSM parser object
osm = OSM(fp)
buildings = osm.get_buildings()
buildings.plot()
```

The script crashes as soon as it hits the first line with the following error:

```
  File "C:\Users\uuaa\miniconda3\envs\env_name\lib\site-packages\geopandas\_vectorized.py", line 39, in <dictcomp>
    type_mapping = {p.value: _names[p.name] for p in pygeos.GeometryType}
KeyError: 'MISSING'
```

Does anyone know why it won't successfully import `OSM` from `pyrosm`? Thanks

**Comment by HTenkanen** [comment]
@awa5114: Hmm the error is not coming from pyrosm but from geopandas. This most probably relates to this issue: https://github.com/geopandas/geopandas/issues/1793 . 

Could you try and update your geopandas to a newer version and see if that helps?

Cheers,
Henrikki
