### ISSUE TITLE
List out of index when reading road networks

### ISSUE THREAD

**Issue by germayneng** [HTenkanen/pyrosm#148]
Good day! 

I have been using pyrosm for more than a year and have been using it to extract tags from pbf files automatically. However, I am getting this error which I am not sure what might cause this issue. I have maintained my own pbfs. I hope you can help me with it.

(the pbf are some private pbfs so I cannot share them) 

```
<ipython-input-4-46c1b19db87f> in <module>
      2 osm = OSM(os.path.join(pbf_path,"private.osm.pbf"))
      3 data = osm.get_network(
----> 4         network_type="all", extra_attributes=None
      5     )

/opt/conda/lib/python3.7/site-packages/pyrosm/pyrosm.py in get_network(self, network_type, extra_attributes, nodes)
    209             network_filter,
    210             self.bounding_box,
--> 211             slice_to_segments=nodes,
    212         )
    213 

/opt/conda/lib/python3.7/site-packages/pyrosm/networks.py in get_network_data(node_coordinates, way_records, tags_as_columns, network_filter, bounding_box, slice_to_segments)
     44         bounding_box,
     45         parse_network=True,
---> 46         calculate_seg_lengths=slice_to_segments,
     47     )
     48 

/opt/conda/lib/python3.7/site-packages/pyrosm/frames.pyx in pyrosm.frames.prepare_geodataframe()

/opt/conda/lib/python3.7/site-packages/pyrosm/frames.pyx in pyrosm.frames.prepare_geodataframe()

/opt/conda/lib/python3.7/site-packages/pyrosm/frames.pyx in pyrosm.frames.prepare_way_gdf()

/opt/conda/lib/python3.7/site-packages/pyrosm/geometry.pyx in pyrosm.geometry.create_way_geometries()

/opt/conda/lib/python3.7/site-packages/pyrosm/geometry.pyx in pyrosm.geometry._create_way_geometries()

IndexError: list index out of range

```

**Comment by HTenkanen** [comment]
Hi @germayneng, and sorry to hear that you have had issues with pyrosm. This problem actually sounds familiar, as I have received a similar error myself earlier. I fixed it and it is already available in the master branch. Could you try installing the pyrosm directly from the master and report whether that solves this issue?

**Comment by germayneng** [comment]
hi @HTenkanen. I have been a fan of your library and have been using them! it is just that I am not sure what caused this error. There are some recent updates for the particular pbf on my end by the team. 

i just tried building from master but still am getting the error. Do you know why this happens?

**Comment by HTenkanen** [comment]
Hmm, it's unfortunately a bit tricky to say what the exact problem is without seeing the data. 😕 The reason relates to parsing the geometry from given way coordinates but what exactly is happening is not clear. In my case, there were certain lat/lon values in the data that were incorrect (larger than the extent of the world's bounds). But this is fixed in [here](https://github.com/HTenkanen/pyrosm/blob/master/pyrosm/geometry.pyx#L303), so that should not be the reason in your case. The most likely point of failure is on [these lines](https://github.com/HTenkanen/pyrosm/blob/master/pyrosm/geometry.pyx#L400-L401) when the coordinates of given way are accessed, i.e. for a reason or another there is not correct information about the node-ids for given way. 

Hence, I would recommend checking that the node-id lists in your way records look correct. You can access the way elements of your PBF like this:

```python

# Initialize
osm = OSM(os.path.join(pbf_path,"private.osm.pbf"))

# Read the PBF records but do not try to construct geometries yet
osm._read_pbf()

# Access the 'raw' way records
osm._way_records

# Access the 'raw' relations
osm._relations
``` 

From those `way_records`, I would check whether the `nodes` attribute of the records looks correct. I.e. there should be a list of node-ids that are used to parse the way geometry (coordinates are fetched from node elements based on node-ids).

**Comment by HTenkanen** [comment]
> I updated to the latest as well as master but still encountering this

How did you install the `master` branch version? (just trying to ensure that you actually use the library built from the source).

**Comment by germayneng** [comment]
let me look into what you suggested and report. I will also think of a way to make this replicable so its easier to understand the problem. 

With regards to your second question, i cloned the repo and 

```
$ python setup.py install
```

**Comment by germayneng** [comment]
Hi @HTenkanen , it is really insightful. Based on my PBF and the code snippet you linked, my guess is that for `u` and `v`, it takes references to the first and last element of the node index. 

From here, where do i access the geometries it tries to take reference from? I think the out of list index error meant that one of the node element is outside the maximum entry of geometries. I want to check the list of geometries as well

**Comment by germayneng** [comment]
looking at the code, it seems to be this `node_coordinates` list. Will be good to guide me on it!

**Comment by germayneng** [comment]
Update:

I checked through all the way IDs and checked their nodes. i have found 5 IDs with no node index. could this be the issue?

**Comment by HTenkanen** [comment]
@germayneng Yes, that could be the issue. However, an empty list should not cause issues because that is handled, so I wonder what else could it be. 🤔 Is there an empty list as nodes with those ways missing the IDs or is there something else? If there is something else, that could explain this.

**Comment by germayneng** [comment]
i iterate through all the way IDs to check if their nodes belong in the node_coordinate list and only found the cases of these way IDs having no nodes. There seems to be no other way IDs that are flagged out. I am doing this because of 

```
IndexError: list index out of range
```

> is there an empty list as nodes with those ways missing the IDs or is there something else? If there is something else, that could explain this.

sorry I don't get this part. The search starts from the way IDs and loop for each node index, find the appropriate coordinates from `node_coordinates` correct? So the only way for out of index error is for node index that does not exist in `node_coordinates` or am I missing other cases?

**Comment by HTenkanen** [comment]
> The search starts from the way IDs and loop for each node index, find the appropriate coordinates from node_coordinates correct? So the only way for out of index error is for node index that does not exist in node_coordinates 

Okay, so did I understand correctly that there were cases where the node-id (of a way) didn't exist in `node_coordinates`? Just to confirm that I understood you correctly. If this is the case, then I think what is the problem, and how to deal with it 👍🏻

**Comment by germayneng** [comment]
> Okay, so did I understand correctly that there were cases where the node-id (of a way) didn't exist in node_coordinates? Just to confirm that I understood you correctly. If this is the case, then I think I know what is the problem, and how to deal with it

From my code, it was cases where the node-id of a way is empty. There are no cases where node-id of a way didn't exist in `node_coordinates`. Those that got a FALSE (not present in `node_coordinates` where because the node-ids are [] 

I think the issue is the pbf and we are looking directly on the pbf

**Comment by HTenkanen** [comment]
@germayneng Did you find an issue with your PBF or is this still an unresolved issue?

**Comment by germayneng** [comment]
we revert back to our previous version of pbf. I have not got the update on the cause. But this is not a blocker on my end. Will update you the cause to see if pyrosm can catch it

**Comment by germayneng** [comment]
@HTenkanen i believe we found duplicated way ids in our pbf which is causing this issue. I do not think there is any action plan i have in mind. Appreciate your prompt reply. Do i close this issue?

**Comment by HTenkanen** [comment]
Ah okay, that might indeed be a reason for this error. Good that you were able to sort this out! 👍🏻
