### ISSUE TITLE
Error -5 while decompressing data: incomplete or truncated stream

### ISSUE THREAD

**Issue by floydluo** [HTenkanen/pyrosm#156]
Hi,

Great works.

I met the following error when I read this pbf file: https://drive.google.com/file/d/136uwnat7eiKYTcesuGLxaa8_vDLM71Ao/view?usp=sharing.

```shell


---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
/var/folders/_j/sxm615tj12ncj326c42h5q9h0000gq/T/ipykernel_74576/3725879886.py in <module>
      1 fp = 'northamerican-1441.pbf'
----> 2 osm = OSM(fp)

~/opt/miniconda3/envs/scrapy/lib/python3.7/site-packages/pyrosm/pyrosm.py in __init__(self, filepath, bounding_box)
     90 
     91         # Get bounding box
---> 92         self._data_bounding_box = get_bounding_box(self.filepath)
     93 
     94         # TODO: Add logging as a parameter?

~/opt/miniconda3/envs/scrapy/lib/python3.7/site-packages/pyrosm/utils/__init__.py in get_bounding_box(filepath)
    191         msg = Blob()
    192         msg.ParseFromString(f.read(blob_header.datasize))
--> 193         blob_data = zlib.decompress(msg.zlib_data)
    194         header_block = HeaderBlock()
    195         header_block.ParseFromString(blob_data)

error: Error -5 while decompressing data: incomplete or truncated stream

```

What can I do for it?

Thanks,

Floyd

**Comment by floydluo** [comment]
To follow up. I find a series of PBF files cannot be read by `pyrosm`, though they are commonly used in different GIS websites. The data I posted above is from 

There is another pbf file URL link:

```
https://ahocevar.com/geoserver/gwc/service/tms/1.0.0/ne:ne_10m_admin_0_countries@EPSG:900913@pbf/3/2/4.pbf
```

It looks like:

![image](https://user-images.githubusercontent.com/18824134/143522421-e4af08ea-c1b1-463e-b7a3-3b16d806ff4a.png)

Obvious, they have `decompressing data: incomplete or truncated stream`. Any idea to open the PBF file like this by `pyrosm`?

Thanks a lot!

**Comment by HTenkanen** [comment]
@floydluo Hmm interesting, thanks for raising this up. If this would have been only a single file, I would have said that it was just a corrupt file, but now it seems that the files are more systematically different. Could you tell a bit more from where these datasets come from and who produces them (if you know)?

The likely reason for these issues is that they have produced the PBF file using some other tool (or with somehow different settings) than what e.g Geofabrik or BBBike uses.

**Comment by HTenkanen** [comment]
@floydluo: Could you also describe a bit more, how you have read that file so that you were able to produce that map? Are you using e.g. QGIS?

**Comment by HTenkanen** [comment]
Hmm, okay I investigated this a bit and it seems that at least the latter example is a TileMapService that has specific layers:
https://ahocevar.com/geoserver/gwc/service/tms/1.0.0

I was able to read it with QGIS:
![image](https://user-images.githubusercontent.com/6659534/143547528-9aa51883-dd1a-4e22-b021-20a26b0a6e3d.png)

This data looks like they are WMS tiles. I don't have much experience with these TileMapServices (hence I might be wrong), but I think the data that you get out from here are not valid OSM.PBF files following the [osm.proto schema](https://github.com/HTenkanen/pyrosm/blob/master/proto/osmformat.proto). Hence, the data is not in a format that would be readable by `pyrosm`. 

Supporting something like this it also out of scope of this library, as the plan is only to support valid [OSM.PBF -files](https://wiki.openstreetmap.org/wiki/PBF_Format).

**Comment by floydluo** [comment]
Hi @HTenkanen,

Thanks a lot for your reply. Actually, I am a layman on OSM and PBF and I learned a lot from your explanation.

You are right, I downloaded the PBF file and drag it to the QGIS to see how it looks like. For the first PBF file, I downloaded it from this website:

![image](https://user-images.githubusercontent.com/18824134/143598367-0d263c91-c7c2-42e6-8d44-fa12d0bd2cb1.png)

This website split the world map into 12 PBF files. But each PBF file seems to be corrupt. I cannot view it via `osmium` either. `osmium` raises the error `PBF error: invalid BlobHeader size (> max_blob_header_size)`.

**Comment by floydluo** [comment]
However, I can open it with QGIS and export it to the GEOJson format. But I find the coordinates are not correct.

The example looks like this:

```json
{ 
    "type": "Feature", 
    "properties": { 
        "centroid": { 
            "type": "Point", 
            "coordinates": [ -72.601105, 5.847051 ] 
        }, 
        "way_json_envelope": { 
            "type": "Polygon", 
            "coordinates": [ [ [ -73.210198, 5.363898 ], [ -73.210198, 6.327202 ], [ -72.048598, 6.327202 ], [ -72.048598, 5.363898 ], [ -73.210198, 5.363898 ] ] ] 
        }
    }, 
    "geometry": { 
        "type": "MultiPolygon", 
        "coordinates": [ 
            [ [ [ 2444.0, 145.0 ], [ 2451.0, 139.0 ], [ 2455.0, 139.0 ], [ 2456.0, 135.0 ], [ 2454.0, 130.0 ], [ 2450.0, 129.0 ], [ 2450.0, 125.0 ], [ 2448.0, 127.0 ], [ 2447.0, 126.0 ], [ 2443.0, 123.0 ], [ 2442.0, 123.0 ], [ 2439.0, 129.0 ], [ 2438.0, 127.0 ], [ 2435.0, 129.0 ], [ 2435.0, 130.0 ], [ 2433.0, 130.0 ], [ 2430.0, 137.0 ], [ 2433.0, 136.0 ], [ 2439.0, 143.0 ], [ 2442.0, 143.0 ], [ 2442.0, 141.0 ], [ 2444.0, 145.0 ] ] ] 
        ] 
    } 
}

```

You can see that `centroid` and `way_json_envelope` have correct coordinates. But coordinates in `geometry` are weird. 

Is this format designed specially for the PBF file? Is there any algorithm I can use to convert the `geometry`'s coordinates into normal ones? 

It will be a great help if you can give me a hint on that. Thanks very much!

**Comment by HTenkanen** [comment]
@floydluo : Yeah, the thing is that PBF is a commonly used data compression format which is not necessary related to OSM.PBF at all. Hence, the files that you've tried to read with pyrosm or osmium won't work because the datasets that you have downloaded are just spatial data layers that have been compressed with PBF, but not containing the data in a format that is supported by these OSM data-reader tools. 

In your GeoJSON file the coordinates of the "geometry" look correct but they are in a metric coordinate reference system (i.e. EPSG:900913) which you have defined in the request. If you change the request to WGS84 (EPSG:4326) they should be in lat/lon format, i.e something like:
`https://ahocevar.com/geoserver/gwc/service/tms/1.0.0/ne:ne_10m_admin_0_countries@EPSG:4326@pbf/3/2/4.pbf`

**Comment by floydluo** [comment]
Wow, amazing! It works. Thanks so much! I really learned a lot from your work and explanation. Appreciate your patience with the GIS amateur like me a lot!

![image](https://user-images.githubusercontent.com/18824134/143611903-e36a9abc-2e55-4d2b-a50d-0d8079c9fd2b.png)
