### ISSUE TITLE
pyrosm import does not work since last update

### ISSUE THREAD

**Issue by kleikemper** [HTenkanen/pyrosm#159]
Since last update, the line

from pyrosm import OSM, get_data

produces the following error:

TypeError: C function cykhash.khashsets.Int64Set_from_buffer has wrong signature (expected PyObject *(__Pyx_memviewslice, int __pyx_skip_dispatch, struct __pyx_opt_args_7cykhash_9khashsets_Int64Set_from_buffer *__pyx_optional_args), got struct __pyx_obj_7cykhash_9khashsets_Int64Set *(__Pyx_memviewslice, int __pyx_skip_dispatch, struct __pyx_opt_args_7cykhash_9khashsets_Int64Set_from_buffer *__pyx_optional_args))

**Comment by HTenkanen** [comment]
Hi @kleikemper, see this issue for solution and explanation why this happens #153

**Comment by kleikemper** [comment]
> Hi @kleikemper, see this issue for solution and explanation why this happens #153

Thanks for the quick response!
