### ISSUE TITLE
Update the codebase for latest pygeos/shapely

### ISSUE THREAD

**Issue by HTenkanen** [HTenkanen/pyrosm#191]
Pygeos and shapely have been updating significantly. Update the codebase to reflect these changes. 

Relates to #182 #146

**Comment by acmeguy** [comment]
Shapely 1.8.5 does not work properly on my mac with Python 3.10.8.
Shapely 2 does.

pyrosm does not work with Shapely 2 and I can not figure out the refactoring required.


Can you please make a version available that works with Shapely 2 or add patch information here (or point to pull request if one exists)

**Comment by acmeguy** [comment]
@HTenkanen - Are you referring to the lgeos issue?

**Comment by HTenkanen** [comment]
Closed by #214
