### ISSUE TITLE
ModuleNotFoundError: No module named 'pyrosm_proto'

### ISSUE THREAD

**Issue by tbdger** [HTenkanen/pyrosm#207]
Can't run the package due to an apparently missing module: pyrosm_proto.

Returns error message below

`    from pyrosm_proto import BlobHeader, Blob, HeaderBlock
ModuleNotFoundError: No module named 'pyrosm_proto'`

**Comment by HTenkanen** [comment]
Hmm, this sounds a bit like you have cloned the repository and try to run it directly from there? 

Try installing the new version of `pyrosm` v0.6.2 with `pip` or from `conda-forge` and try again. Feel free to re-open this issue, if you still have issues after updating the package.
