### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by nlehuby** [HTenkanen/pyrosm#36]
I can't install pyrosm:

When I `pip install pyrosm`, I get a very long stack trace that ends like this:
```
 pyrosm/data_filter.pyx:186:11: 'Int64Set_from_buffer' is not a constant, variable or function identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d8e3udyj/pyrosm/setup.py", line 107, in <module>
        compiler_directives={'language_level': "3",
      File "/home/nlehuby/.local/share/virtualenvs/python-JOH7DBZn/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
        cythonize_one(*args)
      File "/home/nlehuby/.local/share/virtualenvs/python-JOH7DBZn/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: pyrosm/data_filter.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

I'm on ubuntu, and here is my config:
* `python --version`: `Python 3.7.7`
* `pip --version`: `pip 20.1 from /home/nlehuby/.local/share/virtualenvs/python-JOH7DBZn/lib/python3.7/site-packages/pip (python 3.7)`

It collects `pyrosm-0.5.2.tar.gz`

**Comment by HTenkanen** [comment]
@nlehuby Thanks for reporting this, and sorry for your issues regarding the installation. 

Seems to be an issue that the [cykhash](https://github.com/realead/cykhash) library isn't installing properly for some reason. 

Before installing pyrosm can you try installing cykhash with:
`$ pip install https://github.com/HTenkanen/cykhash/archive/master.zip`

And after that try to install pyrosm. 

By the way: are you using conda or virtualenv for managing environments? I haven't tested installations with virtualenv (installation tests are done using conda), so there might be some things that requires fixing.

**Comment by nlehuby** [comment]
Thanks for your quick answer. I'm using [pipenv](https://pipenv.pypa.io/en/latest/) to manage my virtualenv and dependancies.

Indeed, I can't install cykhash:
```   
 x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/home/nlehuby/.local/share/virtualenvs/python-JOH7DBZn/include/python3.7m -c src/cykhash/khashsets.c -o build/temp.linux-x86_64-3.7/src/cykhash/khashsets.o
    src/cykhash/khashsets.c:17:10: fatal error: Python.h: Aucun fichier ou dossier de ce type
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/nlehuby/.local/share/virtualenvs/python-JOH7DBZn/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0ikx2ell/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0ikx2ell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v9zuy5r4/install-record.txt --single-version-externally-managed --compile --install-headers /home/nlehuby/.local/share/virtualenvs/python-JOH7DBZn/include/site/python3.7/cykhash Check the logs for full command output.
```

**Comment by nlehuby** [comment]
Ok, I found the issue, I could not build C code from python3 code because I was using a `python3-dev` for python 3.6 instead of python 3.7.

I've updated the `python3-dev` package and successfully managed to install cykhash and then pyrosm :tada:
Will try a normal pyrosm install from scratch now.

**Comment by HTenkanen** [comment]
@nlehuby Okay, great that you were able to solve this. 👍 Let me know if you continue to have some issues.

**Comment by nlehuby** [comment]
Everything is ok, and it works out of the box with pipenv by the way.
Thanks for your support.

**Comment by HTenkanen** [comment]
@nlehuby Great to hear! 👍 Feel free to raise new issues if you find something that isn't working or if you have other ideas how to improve the tool. 🙂
