### ISSUE TITLE
Feature request: Regular expressions for use within filters, read complete osm.pbf file

### ISSUE THREAD

**Issue by srenoes** [HTenkanen/pyrosm#45]
I wanted to extract all addr: related objects from an osm.pbx file and tried several ways. Excluding doesnt seem to work as an empty gdf is returned. Constructing a full gdf with all data was not easily done either.

Now I thought it would be nice to have the possibilities to use regular expressions in general,
and alone reading a complete osm.pbf file into a geodataframe is very valuable as well.

**Comment by HTenkanen** [comment]
Hi @srenoes! Thanks for your message. 

What do you mean by "all data" here exactly? Could you explain a bit more what kind of data you want to parse from OSM and for what purpose? Constructing a "full gdf" with everything from a given OSM is not something I have heard people to be needing before, so would like to understand what kind of use case this is. 

If you want to dive deeper into the OSM data before any filtering is conducted (i.e. having all the data in original format), the `nodes`, `ways` and `relations` can be accessed via attributes:
  - `osm._nodes`
  - `osm._way_records`
  - `osm._relations`

Note that if you use those, you need to filter/construct the data yourself. All the nodes from the OSM can also be extracted directly as a GeoDataFrame via `osm._nodes_gdf`.

**Comment by HTenkanen** [comment]
@srenoes Closing this issue now. I don't have plans to support regular expressions at the moment, but happy to consider r5 a PR for such feature if you would be interested to take a look at implementing such.
