### ISSUE TITLE
Custom filter fails when Tag doesn't exist in dataset

### ISSUE THREAD

**Issue by ericfowler303** [HTenkanen/pyrosm#47]
`'Tags' object has no attribute 'park_ride'
  File "C:\Users\X\AppData\Roaming\Python\Python36\site-packages\pyrosm\pyrosm.py", line 497, in get_pois
    tags_as_columns += getattr(self.conf.tags, k)`

I'm using a custom filter to get POI info. When using a basic filter as shown in the documentation, things work fine. I am using a more detailed filter which includes some more rare tags, which is when this error above occurs. 

Is there a way to ignore if a tag isn't in the underlying dataset but appears in the custom filter? or is there a simple way for me to look at the tags in the loaded dataset, then remove those from the custom filter that aren't in the loaded tags?

**Comment by ericfowler303** [comment]
I saw this in another issue for some background on my setup:

- Running on Windows 10 x64 Python 3.6.6
- Installed using pip and the needed dependency whl files
- I'm using the 'Hawaii' dataset to test with since it's smaller

**Comment by HTenkanen** [comment]
Hi @ericfowler303 thanks for reporting this!

I think this should be doable. 

Could you still add a code snippet that would reproduce this error?

**Comment by ericfowler303** [comment]
`fp = pyrosm.get_data("hawaii")`
`osm = pyrosm.OSM(fp)`
`custom_filter = {'park_ride': ['yes']}`
`pois = osm.get_pois(custom_filter=custom_filter)`
pretty stripped down but you'll get the error since there doesn't seem to be any "park_ride" tags in Hawaii

**Comment by HTenkanen** [comment]
@ericfowler303 Hi! Sorry for taking quite awhile coming back to this, but this is now fixed to the next release that should come out soonish. Example:

![image](https://user-images.githubusercontent.com/6659534/98694175-d2d32500-2379-11eb-8a3e-0682a733f338.png)
