### ISSUE TITLE
Add possibility to export NetworkX graph 

### ISSUE THREAD

**Issue by HTenkanen** [HTenkanen/pyrosm#57]

**Comment by bramson** [comment]
Yes, this.  
There is a now-defunct project OSMgraph (https://github.com/Mapkin/osmgraph) that did this, but it hasn't been developed for 5 years, only works on Py2, and not on Windows.  There is a clear research and business case for transportation network traversals based on this data, so including this capability would greatly enhance this package's value.

**Comment by HTenkanen** [comment]
@bramson Yes, this is more or less implemented already and will hopefully be out next week 👍 There will be functions to export the network to networkx, igraph and pandana as a directed graph.
