### ISSUE TITLE
Data extraction is not working for city "marseille"

### ISSUE THREAD

**Issue by chourmo** [HTenkanen/pyrosm#60]
The city is listed in cities, but trying to get data gives an error

~/anaconda3/lib/python3.7/site-packages/pyrosm/data/__init__.py in get_data(dataset, update, directory)
    133 
    134     elif dataset in sources._all_sources:
--> 135         return retrieve(search_source(dataset),
    136                  update, directory)
    137 

~/anaconda3/lib/python3.7/site-packages/pyrosm/data/__init__.py in search_source(name)
     99                 if name in available2:
    100                     return sources.subregions.__dict__[subregion].__dict__[name]
--> 101     raise ValueError(f"Could not retrieve url for '{name}'.")
    102 
    103 

ValueError: Could not retrieve url for 'marseille'

**Comment by HTenkanen** [comment]
Thanks for reporting! I'll take a look next week. In the meanwhile you can download the PBF from here: https://download.bbbike.org/osm/bbbike/Marseille/

**Comment by HTenkanen** [comment]
@chourmo Hmm, could you send me a code snippet showing how you try to parse the data for Marseille?
I could not reproduce the error and parsing the data for "`marseille"` works for me:
 
![image](https://user-images.githubusercontent.com/6659534/96424240-1dda9c00-1203-11eb-9f9a-579ec9a254ea.png)

**Comment by chourmo** [comment]
Now it works, weird.
