### ISSUE TITLE
Relational Filter

### ISSUE THREAD

**Issue by sheub** [HTenkanen/pyrosm#64]
Hi Henrikki,
Thx for making useful python library available:)
additionally to the functionalities offered by the library, I am looking for a way to filter OSM data like this:
 e.g all  _playground_ inside _parks_
using overpassAPI I would do it like this:

```
[bbox:{{bbox}}][timeout:1800];

way["leisure"="park"];map_to_area->.a;
( node(area.a)[leisure=playground];
  way(area.a)[leisure=playground];
 );
foreach(
  (._;>;);
  is_in;
  way(pivot)["leisure"="park"];
  out geom;
);
```

In other words, is there a way to filter OSMfeatures with distance to other OSMfeatures?

Many thanks,

Sébastien

**Comment by HTenkanen** [comment]
Hi @sheub !

Thanks for your question. Currently there is no way to conduct such queries using Pyrosm directly, and I don't think such filtering will be supported in the near future either. **However**, you can use basic geopandas functionalities to filter your data in a way as you describe, using the following approach:

1. Read all parks with pyrosm
2. Read all playgrounds with pyrosm
3. Conduct spatial join between the two layers to find all playgrounds that are within parks

You can check my course materials to see how spatial join works, if it is not familiar to you:
https://autogis-site.readthedocs.io/en/2019/notebooks/L3/spatial-join.html 

The main idea with pyrosm is to allow using the wider Python ecosystem for geospatial analysis with OSM data, so you can do all sorts of tricks by continuing to work with other libraries that are linked to Geopandas. 

Does this help you with your problem?

**Comment by sheub** [comment]
Hi @HTenkanen ,

Many thanks for your answer and for the link to your course materials. It did help me, and I could solve my problem.
