### ISSUE TITLE
polygon in filtered ways

### ISSUE THREAD

**Issue by der-karl** [HTenkanen/pyrosm#67]
My question is why sometimes there are **polygon** geometries in the filtered ways (lines), and sometimes not (I tried different values from the `custom_filter` and also different places)? What are those polygon geometries?

```
from pyrosm import OSM, get_data
import time

my_place = 'helsinki'
fp = get_data(my_place)
osm = OSM(fp)

# 1: Using filter_type='keep', keep only 'river' and 'stream' in waterway
waterways_keep = ['river', 'stream']

my_rivers_streams = osm.get_data_by_custom_criteria(custom_filter={
    'waterway': waterways_keep},
    filter_type='keep',
    keep_nodes=False,
    keep_ways=True,
    keep_relations=True)

my_rivers_streams['geom_type'] = my_rivers_streams.geometry.geom_type
print(my_rivers_streams['geom_type'].unique())
# out: ['LineString' 'Polygon']

# 2: Using filter_type='keep', keep only 'river' in waterway
waterways_keep = ['river']

my_rivers = osm.get_data_by_custom_criteria(custom_filter={
    'waterway': waterways_keep},
    filter_type='keep',
    keep_nodes=False,
    keep_ways=True,
    keep_relations=True)

my_rivers['geom_type'] = my_rivers.geometry.geom_type
print(my_rivers['geom_type'].unique())
# out: ['LineString']

```

**Comment by HTenkanen** [comment]
@der-karl Hi!

This relates to a perhaps a bit unintuitive definitions used by OpenStreetMap. So how OSM defines a "way" is not necessarily related to line-geometries (i.e. streets), but they are also used to construct closed geometries such as linear rings or polygons. See here for further documentation: https://wiki.openstreetmap.org/wiki/Way

Pyrosm follows this OSM stucture, and hence "way" features can contain LineString, Polygon or LinearRing geometries. The documentation seems to be missing details about this, so good that you asked 👍 

If you want to filter out only LineString geometries, it can be done easily in GeoPandas:
```python
from pyrosm import OSM, get_data

my_place = 'helsinki'
fp = get_data(my_place)
osm = OSM(fp)

waterways_keep = ['river']

my_rivers = osm.get_data_by_custom_criteria(custom_filter={
    'waterway': waterways_keep},
    filter_type='keep',
    keep_nodes=False,
    keep_ways=True,
    keep_relations=True)

my_rivers['geom_type'] = my_rivers.geometry.geom_type

# Filter line geometries (something like following should work)
line_rivers = my_rivers.loc[my_rivers["geom_type"].isin(["LineString", "MultiLineString"])]

```

**Comment by der-karl** [comment]
thanks @HTenkanen for your quick feedback, yeah I expected to get only 'LineString' and 'MultiLineString'. Your method works fine, thanks.

**Comment by bramson** [comment]
I also have a question related to this.
In the OSM data there are walking areas (such as inside train stations and large sidewalks and public "squares" (of various shapes).  I attached an example with many of these pedestrian areas.  

These are polygon ways in OSM, and they are areas where people can walk.  So, when generating the walking network, and especially when exporting it to NetworkX,, my expectation is that these polygons are simply removed.  

However, in terms of accessibility, it seems it would be better to interpret them as part of the network...perhaps simply by making the polygon boundary a LinearRing or LineString.  The next issue would be, are they even connected to the surrounding network?

![walkNetwork-OSM-ShibuyaStation-PedestrianAreaExample](https://user-images.githubusercontent.com/16698232/99509017-97afa200-29c8-11eb-9c39-3a7bbc165815.png)

**Comment by HTenkanen** [comment]
@bramson Thanks for pointing this out! Currently, they are not handled in any manner (I actually need to check what happens in these cases). But yes, this is something that needs to be taken into account, and in terms of walking areas, I think probably the easiest way to solve this would be to do as you described and possibly generate extra LineStrings that would allow e.g. passing through squares etc. 

Could you @bramson make an issue about this so it can be included in the next iteration of pyrosm?
