### ISSUE TITLE
BUG: Can't apply custom filter to bounded data

### ISSUE THREAD

**Issue by bramson** [HTenkanen/pyrosm#80]
As the title says, I get an error when I try to apply a custom filter to bounded data.

After the installation fiasco, I was finally able to use this package to isolate one "Ku" from the Kanto PBF file (using a Shapely geometry object from another dataset as a "bounding_box" [sic] because I couldn't get it from the name "Shibuya" like I can via the Overpass API).  

That worked, and I was able to get a geoPandas dataframe of the walking network in Shinjuku (although I don't know exactly what kinds of "highways" are including/excluded in the "walking network").  Unfortunately, what I really need there is a NetworkX graph of the network, and that can't be built from the geoDF, so I'll need to figure out a different way to process the bounded data into a NetworkX graph

Anyway, where the geoDF would be great is for all the "shops" in my area.  So I did basically a copy/paste of the example in the documentation, and it crashed:

```
thisAreaData = pyrosm.OSM('../Data/OSMData/kanto-latest.osm.pbf', bounding_box=boundingPolygon)
allStoreFilter = {"shop": True, "tourism": True, "amenity": True, "leisure": True}
pois = thisAreaData.get_pois(custom_filter=allStoreFilter)
```
throws

 ```
 File "G:/My Drive/Codebase/ExtractingOSMData_v01.py", line 217, in <module>
    pois = thisAreaData.get_pois(custom_filter=allStoreFilter)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\pyrosm\pyrosm.py", line 540, in get_pois
    self.bounding_box)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\pyrosm\pois.py", line 32, in get_poi_data
    tags_as_columns, bounding_box)

  File "pyrosm\frames.pyx", line 134, in pyrosm.frames.prepare_geodataframe

  File "pyrosm\frames.pyx", line 178, in pyrosm.frames.prepare_geodataframe

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\geopandas\tools\sjoin.py", line 92, in sjoin
    l_idx, r_idx = sindex.query_bulk(input_geoms, predicate=predicate, sort=False)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\geopandas\sindex.py", line 410, in query_bulk
    res = super().query_bulk(geometry, predicate)

  File "C:\WinPython\python-3.6.5.amd64\lib\site-packages\pygeos\strtree.py", line 188, in query_bulk
    return self._tree.query_bulk(geometry, predicate)

TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.
```
The only thing that is different is that instead of using "get_data" for a city (which I couldn't get to work), I have a bounded area of the full Kanto dataset stored locally.  So, is this operation not supported?

**Comment by HTenkanen** [comment]
Hi @bramson! And thanks for pointing out this. I actually noticed the same behavior yesterday and fixed it. You should get things going on by re-installing the latest changes from GitHub. So something like following should work:
`$ pip uninstall pyrosm`
`$ pip install git+https://github.com/HTenkanen/pyrosm.git@master` 

Sorry for the hassle that you've had. 😬 And thanks for bringing these issues to my attention! 🙏 
I aim to publish the new version of the package this week.

**Comment by HTenkanen** [comment]
@bramson And to your other question about building the graph from network. The new version of pyrosm (that you have installed) actually provides functions to export the street network to NetworkX, igraph and pandana. You can read the docs about these from here (still work in progress):
https://pyrosm.readthedocs.io/en/develop/basics.html#export-street-networks-to-graph

**Comment by HTenkanen** [comment]
As you were wondering how the network is constructed  (i.e. the "rules"), you can check those from here:
https://github.com/HTenkanen/pyrosm/blob/master/pyrosm/config/osm_filters.py

But it's a good point that this information should be mentioned in the docs. I will add. 👍

**Comment by bramson** [comment]
I re-reinstalled it earlier today and this worked perfectly.
The walking network does indeed include the types that I wanted to select, so that is also well done for my purposes.
