### ISSUE TITLE
How to keep all components, not just the largest strongly connected one

### ISSUE THREAD

**Issue by bramson** [HTenkanen/pyrosm#88]
The documentation states:

> By default, Pyrosm will only keep connected edges in the output graph (_largest strongly connected component_). This means that all “isolated islands” of the network will be filtered out because those cannot be reached from other parts of the network (you can also disable this behavior, see below).

I looked around, but I couldn't find the parameter to control this behavior.  

The OSM data for my area is terribly dirty and incomplete, among the many problems is many disconnected walking elements (such as pedestrian bridges, tunnels, and parks).  I plan to test some methods to automatically connect these elements to the main network, but to do that I need to keep them.

My guess is that the feature is supported, and perhaps even documented somewhere, but I just couldn't find it.

**Comment by HTenkanen** [comment]
@bramson Thanks! Ah, yes this is something that I planned to write but forget to do it. I will check the docs and ensure that this is mentioned. You can control this behavior by using `retain_all=True` in the `to_graph()` function.

**Comment by HTenkanen** [comment]
Being able to connect these disconnected graph components together somehow automatically is actually a very useful feature (I've been thinking about the same problem). So if you figure out a way to do this, I'd be very interested learning about it, and it would actually be great to have such a possibility as part of pyrosm, if you'd be okay with such an idea. 🙂

**Comment by bramson** [comment]
Sure, If I figure something decent out, then I certainly won't mind sharing the technique.

As I mentioned, I'm currently working on connecting stations to their exits, and the exits to the walking network to facilitate door-to-door route planning via public transit using only BFS.  Unfortunately, in Japan's OSM data, only the subway stations have entrances/exits marked, so the connection of surface trains is problematic...typically there is just one node representing a whole station maybe with 10 exits.  This is my current priority for v0 of my project.  

However, I expect that whatever method I develop to connect stations and exits to the walking network, will be a part of the method to fix wonky road segments.
