### ISSUE TITLE
BUG: creating network creates ghost copies of each node

### ISSUE THREAD

**Issue by bramson** [HTenkanen/pyrosm#97]
I've discovered what looks to be a bug in the `to_graph` algorithm.  
The number of nodes in the graph resulting from `to_graph` is double the number of nodes pulled by `get_network`.  Furthermore, exactly half the nodes in the graph have no `geometry` attribute (which is how I found the problem).
I have not yet checked whether it always does this, or whether it is a byproduct of one of the options I'm using.
I also haven't checked whether the edges are also doubled.

```
thisAreaData = pyrosm.OSM('../Data/OSMData/kanto-latest.osm.pbf', bounding_box=thisBoundingPolygon)
nodes, edges = thisAreaData.get_network(nodes=True, network_type="walking")
print("numNodes1:", len(nodes))   ##---> 104,950
thisWalkingGraph = thisAreaData.to_graph(nodes, edges, graph_type="networkx", osmnx_compatible=False, retain_all=True)
print("numNodes2:", walkingNetwork.number_of_nodes())    ##---> 209,900
```

**Comment by HTenkanen** [comment]
@bramson Thanks for reporting this! I actually one time popped into this one, but forget about it. 

This behavior is a bit weird and it relates to building networkx graph. I haven't seen similar happening with igraph or pandana (haven't done a proper check though). For some reason, networkx doubles the number of nodes in the graph when it is constructed. 🤔 Need to investigate more..

**Comment by HTenkanen** [comment]
@bramson Would you happen to have a clipped PBF file of the region that produces this bug? I don't seem to be able to reproduce this behavior so it's a bit difficult to debug.. 🤔 Parsing the networkx graph from Tokyo at least works as I would assume.

**Comment by HTenkanen** [comment]
Ha, now I was able to reproduce. It seems to happen when using `osmnx_compatible=False`.

**Comment by HTenkanen** [comment]
@bramson Okay, found the issue. You can get it fixed by installing from master, once all the tests have passed and the merge is ready.
